# Generated by Django 2.1.5 on 2019-01-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('emailid', models.CharField(max_length=25)),
                ('password', models.TextField(default='null')),
                ('contact', models.CharField(max_length=25)),
            ],
        ),
    ]
