# Generated by Django 2.1.5 on 2019-01-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='register',
        ),
    ]
