# Generated by Django 2.1.5 on 2019-01-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20190124_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='property_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=30)),
                ('property_details', models.CharField(max_length=100)),
                ('about_location', models.CharField(max_length=100)),
                ('facilities', models.CharField(max_length=100)),
                ('property_image', models.ImageField(blank=True, upload_to='property_image')),
            ],
        ),
    ]
