# Generated by Django 2.1.5 on 2019-01-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_property_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_details',
            name='propertyi',
            field=models.ImageField(blank=True, upload_to='propertyi'),
        ),
    ]
