# Generated by Django 2.1.5 on 2019-01-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20190128_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_details',
            name='about_location',
            field=models.CharField(max_length=1350),
        ),
        migrations.AlterField(
            model_name='property_details',
            name='facilities',
            field=models.CharField(max_length=1350),
        ),
        migrations.AlterField(
            model_name='property_details',
            name='property_details',
            field=models.CharField(max_length=1350),
        ),
    ]
