# Generated by Django 2.1.5 on 2019-02-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20190128_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25)),
                ('website', models.CharField(max_length=25)),
                ('timing', models.CharField(max_length=25)),
            ],
        ),
    ]
