# Generated by Django 2.1.5 on 2019-02-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_auto_20190201_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_company',
            old_name='email',
            new_name='email_id',
        ),
    ]
