# Generated by Django 2.1.5 on 2019-02-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_auto_20190201_2037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about_company',
            new_name='about_builders',
        ),
    ]
